// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SignalRTestApp.Models;

public partial class message
{
    [Key]
    public int id { get; set; }

    public string messagetxt { get; set; }

    [StringLength(50)]
    public string username { get; set; }
}